name: transvae
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.8.16
  - pip:
    - torch==1.7.1
    - numpy==1.18.5
    - seaborn==0.12.2
    - matplotlib==3.3.2
    - ipykernel==6.23.1
    - scipy==1.5.0
    - pandas==1.1.3
    - scikit-learn==0.23.2
    - rdkit==2023.3.1